apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sic-api
  namespace: apiglu-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sic-api
    spec:
      containers:
      - env:
        - name: SRV_PORT
          valueFrom:
            configMapKeyRef:
              key: SRV_PORT
              name: apiglu-config-dev
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              key: DB_NAME
              name: apiglu-config-dev
        - name: MONGO_STRING
          valueFrom:
            configMapKeyRef:
              key: MONGO_STRING
              name: apiglu-config-dev
        name: sic-api
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
          - containerPort: 80
      imagePullSecrets:
      - name: pipeline-docker-registry
---
kind: Service
apiVersion: v1
metadata:
  name: sic-api
  namespace: apiglu-dev
spec:
  type: NodePort
  selector:
    app: sic-api
  ports:
  - protocol: TCP
    port: 80